Repository WEC-Sim/WEC-Sim, pull requests merged in 2020-12, with the labels that each got.

#444 Fix for CI-B2B bug
  source/lib/WEC-Sim/WECSim_Lib.slx
  source/objects/bodyClass.m
Labels: bug, high, version issue

#472 Paraview pressure fix
  source/functions/paraViewVisualization.m
  source/functions/postProcess.m
  source/objects/bodyClass.m
  source/objects/mooringClass.m
  source/objects/responseClass.m
  source/objects/waveClass.m
  source/wecSim.m
Labels: bug, visualization

#467 Hydrostatic force updates
  docs/man/advanced_features.rst
  source/lib/WEC-Sim/WECSim_Lib.slx
Labels: bodyClass, high

#478 update Read_AQWA
  source/functions/BEMIO/Read_AQWA.m
Labels: BEMIO, bug

#485 PTO-Sim library update resolves #247
  source/lib/PTO-Sim/PTOSim_Lib.slx
Labels: PTO-Sim, bug

#486 Variant subsystem label fix resolves #479
  source/lib/WEC-Sim/WECSim_Lib.slx
  source/objects/bodyClass.m
  source/objects/responseClass.m
  source/wecSim.m
Labels: bug

#456 Add Requested Docs Changes From #369
  docs/index.rst
  docs/man/overview.rst
  docs/man/tutorials.rst
Labels: documentation
