Repository WEC-Sim/WEC-Sim, pull requests merged in 2021-07, with the labels that each got.

#595 Fixes #459. Update ParaView macros for Paraview 5.9
  docs/_include/viz.rst
  source/functions/paraview/pressureGlyphs.py
Labels: Bug, Visualization

#642 Updating ParaView Doc
  docs/_include/viz.rst
  docs/man/advanced_features.rst
Labels: Documentation, Visualization, WEC-Sim Application

#620 restructure CI tests into class-based unit tests
  source/functions/wecSimMCR.m
  tests/bemioTest.m
  tests/passiveYawTest.m
  tests/plotRegressionTests.m
  tests/regressionTest.m
  tests/rotationTest.m
  tests/runFromSimTest.m
  tests/setupAppFiles.m
  tests/setupFromSimFiles.m
  wecSimTest.m
Labels: Enhancement, Tests/CI

#636 BEMIO read mean drift force bug fix
  source/functions/BEMIO/Write_H5.m
Labels: Bug

#641 Troubleshooting Documentation
  .gitignore
  docs/user/advanced_features.rst
  docs/user/getting_started.rst
  docs/user/index.rst
  docs/user/troubleshooting.rst
  docs/user/workflow.rst
Labels: Documentation

#649 Updated applications links in docs
  docs/_include/bemio.rst
  docs/_include/pto.rst
  docs/developer/overview.rst
  docs/introduction/overview.rst
  docs/introduction/release_notes.rst
  docs/user/advanced_features.rst
  docs/user/applications.rst
  docs/user/code_structure.rst
  docs/user/tutorials.rst
Labels: Documentation

#632 Use the caller workspace when reading ptosim outputs
  source/objects/ptoSimClass.m
Labels: PTO-Sim
