Repository WEC-Sim/WEC-Sim, pull requests merged in 2021-04, with the labels that each got.

#553 bugfix for Matlab R2021a
  source/lib/WEC-Sim/WECSim_Lib.slx
Labels: Bug, Version

#560 Pull R2021a bugfix into dev
  source/lib/WEC-Sim/WECSim_Lib.slx
Labels: Bug, Version

#534 Update to Radiation_IRF.m to resolve Issue #517
  source/functions/BEMIO/Normalize.m
  source/functions/BEMIO/Radiation_IRF.m
Labels: Added Mass, Enhancement

#570 Update waveClass in reference to issue #564
  source/objects/waveClass.m
Labels: Bug, Waves
