Repository WEC-Sim/WEC-Sim, pull requests merged in 2021-02, with the labels that each got.

#506 Dev Update to the bodyClass.m
  source/objects/bodyClass.m
Labels: bug

#501 Remove reference to removed method to repair dev docs
  docs/man/api.rst
  source/objects/waveClass.m
Labels: Documentation

#511 Resolving #497 bug with body.cb
  source/objects/bodyClass.m
  source/wecSim.m
Labels: Bug

#509 add WecSim if for MCR loadFile
  docs/man/advanced_features.rst
  source/wecSim.m
Labels: MCR/PCT
