Repository WEC-Sim/WEC-Sim, pull requests merged in 2022-03, with the labels that each got.

#801 Wave class wave gauge update
  docs/user/advanced_features.rst
  source/functions/postProcessWecSim.m
  source/objects/responseClass.m
  source/objects/waveClass.m
Labels: Waves

#806 vectorization of radiationIRF() function
  examples/BEMIO/WAMIT/RM3/bemio.m
  source/functions/BEMIO/excitationIRF.m
  source/functions/BEMIO/radiationIRF.m
Labels: Enhancement, BEM/BEMIO

#816 Fix documentation on dev branch
  docs/README.md
  docs/_include/added_mass.rst
  docs/_include/bemio.rst
  docs/_include/morison_element.rst
  docs/conf.py
  docs/developer/advanced_features.rst
  docs/environment.yml
  source/functions/BEMIO/readWAMIT.m
Labels: Documentation

#814 Bug fix: responseClass reading the MoorDyn Lines.out file too early, resolves #811
  source/functions/postProcessWecSim.m
  source/lib/WEC-Sim/WECSim_Lib_Moorings.slx
Labels: Bug, MoorDyn

#827 fix cable implementation
  source/lib/WEC-Sim/WECSim_Lib_Cables.slx
Labels: Bug, Cable Class

#799 Fix rate transition error
  source/lib/PTO-Sim/PTOSim_Lib.slx
  source/lib/WEC-Sim/WECSim_Lib_Body_Elements.slx
  source/lib/WEC-Sim/WECSim_Lib_Moorings.slx
Labels: Bug, Simulation Class

#822 Refactoring classes and properties - part 2
  docs/_include/added_mass.rst
  docs/_include/bemio.rst
  docs/_include/mooring.rst
  docs/_include/morison_element.rst
  docs/_include/viz.rst
  docs/user/advanced_features.rst
  docs/user/api.rst
  docs/user/code_structure.rst
  docs/user/troubleshooting.rst
  source/functions/BEMIO/readBEMIOH5.m
  source/functions/initializeWecSim.m
  source/functions/paraview/writeParaviewBody.m
  source/functions/paraview/writeParaviewMooring.m
  source/functions/paraview/writeParaviewResponse.m
  source/functions/paraview/writeParaviewWave.m
  source/functions/postProcessWecSim.m
  source/functions/simulink/mask/bodyClassCallback.m
  source/functions/simulink/mask/writeBlocksFromInput.m
  source/functions/simulink/mask/writeInputFromBlocks.m
  source/functions/simulink/model/irregWaveMorison.m
  source/functions/simulink/model/regWaveMorison.m
  source/functions/stopWecSim.m
  source/lib/PTO-Sim/PTOSim_Lib.slx
  source/lib/WEC-Sim/WECSim_Lib_Body_Elements.slx
  source/lib/WEC-Sim/WECSim_Lib_Cables.slx
  source/lib/WEC-Sim/WECSim_Lib_Frames.slx
  source/lib/WEC-Sim/WECSim_Lib_Moorings.slx
  source/objects/bodyClass.m
  source/objects/cableClass.m
  source/objects/simulationClass.m
  source/wecSim.m
  source/wecSimFcn.m
  source/wecSimMCR.m
  source/wecSimPCT.m
  tests/runFromSimTest.m
  wecSimTest.m
Labels: Mooring Class, Simulation Class, Response Class, Body Class, Constraint Class, SCM, Library, Cable Class

#821 New pto sim lib
  docs/_include/pto.rst
  docs/_static/images/AdjustableRodHPTO.png
  docs/_static/images/DirectDrivePorts.png
  docs/_static/images/GeneratorSpeedControl.png
  docs/_static/images/MoTIONMECHANISM.PNG
  docs/_static/images/MotionConversionLib.png
  docs/_static/images/OSWECPTOSimExample.png
  docs/_static/images/PTOSimBlock1.png
  docs/_static/images/PTOSimBlock1OSWEC.png
  docs/_static/images/RM3withPTOSimBlocks.png
  docs/_static/images/SELECTORS.PNG
  docs/_static/images/SELECTORS2.PNG
  docs/_static/images/SliderandCrankMechanism.png
  docs/_static/images/WEC-Sim_Lib_PTOSim.png
  docs/_static/images/WEC-Sim_flowChart.png
  docs/_static/images/code_structure/PTOSimClass_diagram.png
  docs/_static/images/overview/OSWEC_with_ptosim.JPG
  docs/_static/images/overview/OSWEC_with_ptosim.png
  docs/_static/images/pto_sim.PNG
  docs/_static/images/pto_sim_hyd.PNG
  docs/_static/images/pto_sim_lib.png
  docs/_static/images/rotary_to_lin.PNG
  docs/introduction/overview.rst
  docs/user/code_structure.rst
  source/functions/initializeWecSim.m
  source/functions/postProcessWecSim.m
  source/functions/simulink/mask/inputOrCustomCallback.m
  source/functions/simulink/mask/ptoSimClassCallback.m
  source/lib/PTO-Sim/BlockFigures/CheckValve.png
  source/lib/PTO-Sim/BlockFigures/DoubleActingPiston.png
  source/lib/PTO-Sim/BlockFigures/ElectricMotor.png
  source/lib/PTO-Sim/BlockFigures/FixedHydraulicMotor.png
  source/lib/PTO-Sim/BlockFigures/GasAccumulator.png
  source/lib/PTO-Sim/BlockFigures/RectifyingCheckValve.png
  source/lib/PTO-Sim/BlockFigures/RectifyingCheckValveV2.png
  source/lib/PTO-Sim/BlockFigures/VariableDisplacementHydraulicMotor.png
  source/lib/PTO-Sim/PTOSim_Lib.slx
  source/objects/ptoClass.m
  source/objects/ptoSimClass.m
  source/objects/responseClass.m
  source/objects/simulationClass.m
  source/wecSim.m
Labels: Enhancement, PTO-Sim

#828 Refactoring classes and properties - part 3
  examples/OSWEC/OSWEC.slx
  examples/OSWEC/wecSimInputFile.m
  examples/RM3/RM3.slx
  examples/RM3/wecSimInputFile.m
  examples/RM3FromSimulink/RM3FromSimulink.slx
  examples/RM3FromSimulink/wecSimInputFile.m
  source/functions/initializeWecSim.m
  source/functions/postProcessWecSim.m
  source/functions/simulink/mask/bodyClassCallback.m
  source/functions/simulink/mask/waveClassCallback.m
  source/functions/simulink/mask/writeBlocksFromInput.m
  source/functions/simulink/mask/writeInputFromBlocks.m
  source/functions/simulink/mask/writeLineFromVar.m
  source/functions/simulink/model/calcCableTens.m
  source/lib/WEC-Sim/WECSim_Lib_Body_Elements.slx
  source/lib/WEC-Sim/WECSim_Lib_Cables.slx
  source/lib/WEC-Sim/WECSim_Lib_Constraints.slx
  source/lib/WEC-Sim/WECSim_Lib_Frames.slx
  source/lib/WEC-Sim/WECSim_Lib_Moorings.slx
  source/lib/WEC-Sim/WECSim_Lib_PTOs.slx
  source/objects/bodyClass.m
  source/objects/cableClass.m
  source/objects/constraintClass.m
  source/objects/mooringClass.m
  source/objects/ptoClass.m
  source/objects/responseClass.m
  source/objects/simulationClass.m
  source/objects/waveClass.m
  source/wecSimMCR.m
  source/wecSimPCT.m
  tests/RegressionTests/IrregularWaves/irregularCIC/wecSimInputFile.m
  tests/RegressionTests/IrregularWaves/irregularSS/wecSimInputFile.m
  tests/RegressionTests/RegularWaves/regular/wecSimInputFile.m
  tests/RegressionTests/RegularWaves/regularCIC/wecSimInputFile.m
  tests/RegressionTests/RegularWaves/regularSS/wecSimInputFile.m
  tests/rotationTest.m
  tests/runFromSimTest.m
  tutorials/OSWEC/OSWEC_wecSimInputFile.m
  tutorials/OSWEC/wecSimInputFile.m
  tutorials/RM3/RM3_wecSimInputFile.m
  tutorials/RM3/wecSimInputFile.m
Labels: Mooring Class, PTO Class, MoorDyn, Simulation Class, Response Class, Body Class, Constraint Class, SCM, Cable Class

#817 Move documentation compilation to GitHub Actions
  .github/workflows/docs.yml
  .travis.yml
  docs/README.md
  docs/_assets/gh-pages.gitignore
  docs/_include/added_mass.rst
  docs/_include/viz.rst
  docs/conf.py
  docs/developer/advanced_features.rst
  docs/environment.yml
Labels: Documentation

#826 Warning/Error flags
  source/functions/initializeWecSim.m
  source/objects/bodyClass.m
  source/objects/cableClass.m
  source/objects/constraintClass.m
  source/objects/mooringClass.m
  source/objects/ptoClass.m
  source/objects/ptoSimClass.m
  source/objects/responseClass.m
  source/objects/simulationClass.m
  source/objects/waveClass.m
Labels: SCM

#838 Refactoring - Update class setAccess and getAccess
  examples/RM3/wecSimInputFile.m
  source/functions/initializeWecSim.m
  source/objects/bodyClass.m
  source/objects/cableClass.m
  source/objects/constraintClass.m
  source/objects/mooringClass.m
  source/objects/ptoClass.m
  source/objects/simulationClass.m
  source/objects/waveClass.m
Labels: SCM

#832 Refactoring classes and properties - part 4
  docs/conf.py
  source/functions/BEMIO/calcSpectralMoment.m
  source/functions/BEMIO/calcWaveNumber.m
  source/functions/BEMIO/readNEMOH.m
  source/functions/initializeWecSim.m
  source/functions/paraview/paraviewVisualization.m
  source/functions/stopWecSim.m
  source/lib/WEC-Sim/WECSim_Lib_Body_Elements.slx
  source/lib/WEC-Sim/WECSim_Lib_Cables.slx
  source/objects/bodyClass.m
  source/objects/responseClass.m
  source/objects/simulationClass.m
  source/objects/waveClass.m
  source/wecSim.m
  source/wecSimFcn.m
  source/wecSimPCT.m
  tests/RegressionTests/IrregularWaves/irregularCIC/irregularCIC_org.mat
  tests/RegressionTests/IrregularWaves/irregularCIC/runLoadIrregularCIC.m
  tests/RegressionTests/IrregularWaves/irregularSS/irregularSS_org.mat
  tests/RegressionTests/IrregularWaves/irregularSS/runLoadIrregularSS.m
  tests/RegressionTests/RegularWaves/regular/regular_org.mat
  tests/RegressionTests/RegularWaves/regularCIC/regularCIC_org.mat
  tests/RegressionTests/RegularWaves/regularSS/regularSS_org.mat
  tests/bemioTest.m
  tests/regressionTest.m
Labels: Mooring Class, PTO Class, Wave Class, Simulation Class, Response Class, Body Class, Constraint Class, SCM, Library, Cable Class

#839 Remove deprecated functions from the BEMIO API
  docs/_include/bemio.rst
Labels: Bug, Documentation
