Repository WEC-Sim/WEC-Sim, pull requests merged in 2022-08, with the labels that each got.

#929 Fixes saveViz feature for elevation import
  source/objects/responseClass.m
Labels: Bug, Visualization

#917 Fix wave elevation import with rampTime = 0
  source/functions/simulink/model/irregWaveMorison.m
  source/functions/simulink/model/noWaveMorison.m
  source/functions/simulink/model/regWaveMorison.m
  source/objects/waveClass.m
Labels: Wave Class

#910 fix non-linear hydro
  source/functions/simulink/model/nonLinearBuoyancy.m
Labels: Non-linear hydro

#904 Property validation for WEC-Sim objects
  source/functions/initializeWecSim.m
  source/lib/WEC-Sim/WECSim_Lib_Cables.slx
  source/objects/bodyClass.m
  source/objects/cableClass.m
  source/objects/constraintClass.m
  source/objects/mooringClass.m
  source/objects/ptoClass.m
  source/objects/ptoSimClass.m
  source/objects/simulationClass.m
  source/objects/waveClass.m
Labels: SCM

#907 Dev: adding ampSpectraForWS function
  docs/user/code_structure.rst
  source/functions/BEMIO/elevationToSpectrum.m
Labels: Wave Class
