Repository WEC-Sim/WEC-Sim, pull requests merged in 2022-04, with the labels that each got.

#840 Refactoring docs
  docs/developer/library.rst
  docs/user/advanced_features.rst
  docs/user/api.rst
  docs/user/code_structure.rst
  docs/user/troubleshooting.rst
  docs/user/tutorials.rst
  source/objects/cableClass.m
  source/objects/constraintClass.m
  source/objects/mooringClass.m
  source/objects/ptoClass.m
  source/objects/simulationClass.m
  source/objects/waveClass.m
Labels: Documentation

#847 Update the WEC-Sim Theory Documentation to Clarify Wave Power Calculation
  .github/workflows/docs.yml
  docs/theory/theory.rst
Labels: Documentation, Wave Class, Theory

#854 Add Google Analytics 4
  docs/_templates/layout.html
Labels: Enhancement, Documentation
