Repository WEC-Sim/WEC-Sim, pull requests merged in 2023-08, with the labels that each got.

#1093 Paraview documentation hyperlink fix
  docs/_include/viz.rst
Labels: Documentation, Visualization

#1092 use capytaine v2 to compute hydrostatics
  .gitignore
  examples/BEMIO/CAPYTAINE/call_capytaine.py
Labels: BEM/BEMIO

#1095 Fix Direct Drive PTO Output order
  source/objects/responseClass.m
Labels: Bug, PTO-Sim

#1096 Update readAQWA.m
  source/functions/BEMIO/readAQWA.m
Labels: Bug, BEM/BEMIO

#1100 Fix accelerator modes issue
  source/functions/initializeWecSim.m
Labels: Bug, Simulation Class

#1101 Pulling master bugfixes into dev
  docs/user/webinars.rst
  source/functions/BEMIO/readAQWA.m
  source/functions/initializeWecSim.m
  source/functions/moorDyn/README.md
  source/functions/simulink/model/nonLinearBuoyancy.m
  source/lib/WEC-Sim/WECSim_Lib_Moorings.slx
  source/objects/responseClass.m
  source/wecSim.m
Labels: Bug

#1102 Update plotRadiationIRF.m
  source/functions/BEMIO/plotRadiationIRF.m
Labels: Documentation

#1098 Update paraview doc images
  docs/README.md
  docs/_include/viz.rst
  docs/index.rst
Labels: Visualization

#1087 readNEMOH update to be compatible with v3.0.0 release (but not QTF)
  source/functions/BEMIO/readNEMOH.m
Labels: Bug, BEM/BEMIO

#1105 Update readNEMOH.m for compatibility with NEMOH v3.0
  source/functions/BEMIO/readNEMOH.m
Labels: Bug
