Repository WEC-Sim/WEC-Sim, pull requests merged in 2023-09, with the labels that each got.

#1106 Add simple direct drive PTO model
  source/blockFigures/simpleDDPTO.png
  source/lib/WEC-Sim/WECSim_Lib_PTOSim.slx
  source/objects/ptoSimClass.m
  source/objects/responseClass.m
Labels: PTO-Sim

#1108 Control+pto docs
  docs/_static/images/piGainSweep.png
  docs/_static/images/piPTOSimulink.png
  docs/_static/images/reactiveWithPTOCC.png
  docs/_static/images/reactiveWithPTOCCPower.png
  docs/_static/images/reactiveWithPTOOpt.png
  docs/_static/images/reactiveWithPTOOptPower.png
  docs/_static/images/reactiveWithPTOSweep.png
  docs/refs/WEC-Sim_Adv_Features.bib
  docs/user/advanced_features.rst
Labels: Control, PTO-Sim

#1071 Implement an FIR filter to calculate radiation forces
  docs/user/advanced_features.rst
  source/functions/initializeWecSim.m
  source/functions/stopWecSim.m
  source/lib/WEC-Sim/WECSim_Lib_Body_Elements.slx
  source/objects/bodyClass.m
  source/objects/simulationClass.m
Labels: Enhancement

#1126 Updating documentation to include links for the Advanced Features Web…
  docs/_static/downloads/advancedFeaturesWebinars/10_WEC-Sim_AdvFeatures_Desal.pdf
  docs/_static/downloads/advancedFeaturesWebinars/11_WEC-Sim_AdvFeatures_Visualization.pdf
  docs/_static/downloads/advancedFeaturesWebinars/1_WEC-Sim_AdvFeatures_MCR_Batch_Runs.pdf
  docs/_static/downloads/advancedFeaturesWebinars/2_WEC-Sim_AdvFeatures_Nonlinear_hydro.pdf
  docs/_static/downloads/advancedFeaturesWebinars/3_WEC-Sim_AdvFeatures_Non_hydro.pdf
  docs/_static/downloads/advancedFeaturesWebinars/4_WEC-Sim_AdvFeatures_B2B.pdf
  docs/_static/downloads/advancedFeaturesWebinars/5_WEC-Sim_AdvFeatures_PTOSim.pdf
  docs/_static/downloads/advancedFeaturesWebinars/6_WEC-Sim_AdvFeatures_Controls.pdf
  docs/_static/downloads/advancedFeaturesWebinars/7_WEC-Sim_AdvFeatures_Cable.pdf
  docs/_static/downloads/advancedFeaturesWebinars/8_WEC-Sim_AdvFeatures_MoorDyn.pdf
  docs/_static/downloads/advancedFeaturesWebinars/9_WEC-Sim_AdvFeatures_OWC_Modeling.pdf
  docs/user/webinars.rst
Labels: Documentation

#1130 Multiple Wave Spectra
  docs/_static/images/Nwave.png
  docs/index.rst
  docs/user/advanced_features.rst
  source/functions/initializeWecSim.m
  source/functions/stopWecSim.m
  source/lib/WEC-Sim/WECSim_Lib_Body_Elements.slx
  source/lib/WEC-Sim/WECSim_Lib_Frames.slx
Labels: Enhancement
