Repository WEC-Sim/WEC-Sim, pull requests merged in 2024-11, with the labels that each got.

#1353 WEC-Sim QTFs compatability with NEMOH
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mechanics/Badd.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mechanics/Inertia.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mechanics/Kh.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mechanics/Km.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh.cal
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh/Description_Full.tec
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh/Description_Wetted.tec
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh/Freesurface.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh/GC_hull.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh/Hydrostatics.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh/Inertia_hull.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh/Integration.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh/KH.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh/Kochin.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh/L10.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh/L12.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh/Mesh.tec
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh/OC3-Hywind_FOWT.tec
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Mesh/OC3-Hywind_FOWT_info.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/Nemoh.cal
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/OC3-Hywind_FOWT1.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/bemio.m
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/results/CA.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/results/CM.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/results/DiffractionForce.tec
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/results/ExcitationForce.tec
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/results/FKForce.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/results/FKForce.tec
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/results/Fe.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/results/Forces.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/results/QTF/OUT_QTFM_N_0.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/results/QTF/OUT_QTFP_N_0.dat
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/results/RadiationCoefficients.tec
  examples/BEMIO/NEMOH/NEMOH_v3.0.2/OC3-Hywind_FOWT/results/index.dat
  source/functions/BEMIO/QTFs/assignIDs.m
  source/functions/BEMIO/QTFs/plotQTFs.m
  source/functions/BEMIO/QTFs/triToFullMatrix.m
  source/functions/BEMIO/plotBEMIO.m
  source/functions/BEMIO/readNEMOH.m
  source/lib/WEC-Sim/WECSim_Lib_Body_Elements.slx
  source/objects/bodyClass.m
Labels: BEM/BEMIO, Theory

#1359 Minor bug fix related to PR #1353
  source/functions/BEMIO/QTFs/plotQTFs.m
  source/functions/BEMIO/QTFs/triToFullMatrix.m
Labels: Bug

#1350 update body library block mask to address #1346 on dev branch
  source/functions/BEMIO/readCAPYTAINE.m
  source/lib/WEC-Sim/WECSim_Lib_Body_Elements.slx
Labels: Bug

#1362 Update overview.rst - fixed a typo
  docs/introduction/overview.rst
Labels: Documentation

#1366 Resolve unit discrepancy from #1356
  source/objects/waveClass.m
Labels: Wave Class

#1369 Update forceInternalMechanics and powerInternalMechanics in PTO blocks
  source/lib/WEC-Sim/WECSim_Lib_PTOs.slx
Labels: Bug
